Version check fixes

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,8 +13,8 @@ function install() {
 
   [ "$install_type" != "version" ] && echo "Install type \"$install_type\" is not supported" && exit 1
   
-  major_version=$(echo $version | cut -d'.' -f1)
-  [[ $major_version -le 1 ]] && echo  "Major version is $major_version but >=2 is required" && exit 1
+  minor_version=$(echo $version | cut -d'.' -f2)
+  [[ $minor_version -le 18 ]] && echo "Version $version requested, but >=0.18.0 is required" && exit 1
 
   local tmp_download_dir=$(mktemp -d)
   local repo="elixir-lsp/elixir-ls"
@@ -32,9 +32,9 @@ function install() {
 
   unzip "${tmp_download_dir}/${download_filename}"
   mkdir -p ./bin
-  ln -s ../language_server.sh ./bin/elixir-ls
-  ln -s ../debug-adapter.sh ./bin/debug-adapter
-  ln -s ../launch.sh ./bin/launch.sh
+  ln -sr ../language_server.sh ./bin/elixir-ls
+  ln -sr ../debug_adapter.sh ./bin/debug_adapter
+  ln -sr ../launch.sh ./bin/launch.sh
   cp -fpr * "${install_path}"
 
   popd >/dev/null
